app:
  name: gin-server
  port: 8080

db:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: rosetta_monitor
  charset: utf8mb4

redis:
  database: 7
  host: 127.0.0.1
  port: 6379
  password:

Auth:
  token: true

